### ISSUE TITLE
Fehler im Script

### ISSUE THREAD

**Issue by vr6syncro** [peoples0815/backitup#1]
function WerteAktuallisieren() {
    setState(instanz + "scriptEnabled.Wandtablet.System.BackitUp_V3", false);
    setStateDelayed(instanz + "scriptEnabled.Wandtablet.System.BackitUp_V3", true, 1000);

ab Zeile 328

**Comment by peoples0815** [comment]
Danke für den Hinweis!

In der Anleitung unter Konfiguration -> 4 Speicherort ist beschrieben, dass genau dieser Eintrag im Bedarfsfall händisch geändert werden muss.

Ich habe es jetzt auf (instanz + "scriptEnabled.BackitUp_V3") geändert, wenn jemand das jedoch wo anders abspeichert muss das wieder angepasst werden.
