### ISSUE TITLE
Adapter löscht total - Backup nicht

### ISSUE THREAD

**Issue by quorle** [peoples0815/backitup#4]
Mir ist leider aufgefallen, dass der Adapter das Total-Backup nicht löscht. Kann das wer bestätigen?
Ich habe eingestellt, dass nur immer ein Backup von total vorhanden sein soll, aber leider löscht er die letzteren nicht. In der Log ist leider nichts zu sehen.

**Comment by peoples0815** [comment]
Bitte hier das issue hinterlassen:
https://github.com/simatec/ioBroker.backitup
Das Script wird nicht mehr weiterentwickelt
